### ISSUE TITLE
Failed to compile: Attempted import error: 'addonReducers' is not exported from '../../../../../src/config'.

### ISSUE THREAD

**Issue by renbro299** [plone/volto#1586]
For the commands, I used "npx @plone/create-volto-app volto" to create the volto instance. I also ran "yarn start".

A screenshot of the error screen is provided below:

<img width="1440" alt="Screen Shot 2020-06-15 at 11 32 40 AM" src="https://user-images.githubusercontent.com/45237427/84691914-f7ce8380-af12-11ea-922a-bae1b0f8c5c0.png">

**Comment by tisto** [comment]
I guess we need to adapt create-volto-app to this change:

https://github.com/plone/volto/pull/1542

@tiberiuichim are you familiar with how create-volto-app works? Could you imagine to have a look?

**Comment by tiberiuichim** [comment]
@tisto sorry, I'm late about this, we're migrating a website today, had a ton of work to do. I saw that @iFlameing solved the issue, bravo!

**Comment by tisto** [comment]
@tiberiuichim we thought so. Though, it is still broken it seems:

```
➜  workspace git:(master) ✗ npm install -g yarn
/Users/timo/.nvm/versions/node/v12.16.1/bin/yarn -> /Users/timo/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/bin/yarn.js
/Users/timo/.nvm/versions/node/v12.16.1/bin/yarnpkg -> /Users/timo/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.4
updated 1 package in 0.431s
➜  workspace git:(master) ✗ npm install -g @plone/create-volto-app
/Users/timo/.nvm/versions/node/v12.16.1/bin/create-volto-app -> /Users/timo/.nvm/versions/node/v12.16.1/lib/node_modules/@plone/create-volto-app/bin/create-volto-app.js
+ @plone/create-volto-app@6.2.0
updated 1 package in 2.226s
➜  workspace git:(master) ✗ create-volto-app myvoltoproject
/Users/timo/.nvm/versions/node/v12.16.1/lib/node_modules/@plone/create-volto-app/volto-starter-kit

Creating myvoltoproject...

⠋ Copying files[Error: ENOENT: no such file or directory, lstat '/Users/timo/.nvm/versions/node/v12.16.1/lib/node_modules/@plone/create-volto-app/volto-starter-kit'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/timo/.nvm/versions/node/v12.16.1/lib/node_modules/@plone/create-volto-app/volto-starter-kit'
}
```

I have no clue how this git submodules magic with volto-starter-kit works. Maybe @nileshgulia1 can help with it...

**Comment by renbro299** [comment]
@iFlameing How did you solve the issue? I am still getting the same errors as before.

<img width="1440" alt="Screen Shot 2020-06-16 at 11 06 06 AM" src="https://user-images.githubusercontent.com/45237427/84792028-6538ed80-afc1-11ea-80a4-c76c613975e1.png">

**Comment by renbro299** [comment]
<img width="1440" alt="Screen Shot 2020-06-16 at 11 14 31 AM" src="https://user-images.githubusercontent.com/45237427/84793032-9c5bce80-afc2-11ea-8436-c3e15222ead5.png">

**Comment by iFlameing** [comment]
Somehow our new release not populating the volto-starter-kit. I am working on it. But if you want to develop locally. You have to do some steps.
1. clone the repo
2. install the dependency
3. run this command
4. ```git submodule init```
5. npm link
6. create-volto-app  volto and you will able to create volto app.

I am investigating why volto-starter-kit, not auto-populating.

**Comment by iFlameing** [comment]
@renbro299 please use this npm install git+https://github.com/plone/create-volto-app

**Comment by renbro299** [comment]
Done. It worked. Thank you!

**Comment by tisto** [comment]
@renbro299 can you please try again with the latest release:

https://www.npmjs.com/package/@plone/create-volto-app/v/6.2.1

**Comment by iFlameing** [comment]
@tisto It will not work. I tested it out somehow the submodule is not populated. we have to go with the git version. we should together look into it tomorrow ;(

**Comment by iFlameing** [comment]
we still getting the copy error because volto-starter-kit is not present in nodemodules/@plone/create-volto-app

**Comment by nileshgulia1** [comment]
@tisto @tiberiuichim Just seen the messages. Having too work load these days, will get back to look on this in couple of days.

**Comment by tiberiuichim** [comment]
I have this error after creating a new volto project with:

```
npx @plone/create-volto-app volto
```

```
/home/tibi/work/my-volto-app/node_modules/resolve/lib/sync.js:74
    var err = new Error("Cannot find module '" + x + "' from '" + parent + "'");                                                                                                      ^

Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                                                                    Error: Cannot find module '@babel/plugin-proposal-function-bind' from '/home/tibi/work/my-volto-app'
```

**Comment by tiberiuichim** [comment]
I was able to avoid the above problem (which happened at ``yarn start``) by replacing the local yarn.lock with the copy from volto master:

```
rm yarn.lock
wget https://raw.githubusercontent.com/plone/volto/master/yarn.lock
``

**Comment by tiberiuichim** [comment]
And now I have this error in the browser console:

```
webpackHotDevClient.js:15 Uncaught Error: Cannot find module 'webpack-dev-server/client/utils/createSocketUrl'
    at webpackMissingModule (webpackHotDevClient.js:15)
    at Object.<anonymous> (webpackHotDevClient.js:15)
    at Object../node_modules/razzle-dev-utils/webpackHotDevClient.js (webpackHotDevClient.js:276)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Object.0 (theme.js:1)
    at __webpack_require__ (bootstrap:853)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at vendors~client.chunk.js:1
```

**Comment by iFlameing** [comment]
@tiberiuichim somehow submodule is not populating in new release. That's why it is giving error. The npm not installing the volto starter kit as submodule.

You can see the changes in 6.0.0 and current release.

I don't have much knowledge regarding git submodule that's why I am unable to fix that. 

Can you take a look at create-volto-app repo why sumodule is not populating. You can use got version if you want. It is working perfectly fine .

You can find in above comments

**Comment by tiberiuichim** [comment]
@iFlameing now I got it working. I've used the official method, installing create-volto-app globally instead of using npx.

**Comment by iFlameing** [comment]
@tiberiuichim did you use latest release 6.2.0

**Comment by iFlameing** [comment]
Well git version is working.

**Comment by tiberiuichim** [comment]
Released version doesn't work:
```
 I  ~/work  npm i -g @plone/create-volto-app                                                                                            Wed 17 Jun 2020 05:58:45 PM UTC/home/tibi/.node_modules/bin/create-volto-app -> /home/tibi/.node_modules/lib/node_modules/@plone/create-volto-app/bin/create-volto-app.js
+ @plone/create-volto-app@6.2.1
updated 1 package in 5.139s
 I  ~/work                                                                                                                       5.4s  Wed 17 Jun 2020 05:59:00 PM UTC I  ~/work  create-volto-app my-volto-app                                                                                               Wed 17 Jun 2020 05:59:05 PM UTC/home/tibi/.node_modules/lib/node_modules/@plone/create-volto-app/volto-starter-kit

Creating my-volto-app...

⠋ Copying files[Error: ENOENT: no such file or directory, lstat '/home/tibi/.node_modules/lib/node_modules/@plone/create-volto-app/volto-starter-kit'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/tibi/.node_modules/lib/node_modules/@plone/create-volto-app/volto-starter-kit'
}
> Error! Copy command failed, try again.
```

**Comment by iFlameing** [comment]
Fixed in the latest release @6.2.3. Now you can install the @plone/create-volto-app globally using npm as well as yarn

```bash
npm install -g @plone/create-volto-app
```

**Comment by iFlameing** [comment]
I am also closing this because it is fixed :)
