### ISSUE TITLE
UX: Make "+" more obvious (was: Volto editor first time use, adding images is difficult)

### ISSUE THREAD

**Issue by fredvd** [plone/volto#682]
I tested the Volto editor last week as a complete newbie: I didn't look at any screencasts the last few months or documentation so I was as 'blank as possible'.  I first played around on the Volto demo site and later installed Volto with locally because I really thought at first something was wrong with the online demo site. 

This is a 'curse of knowledge' issue: once you know how it works, the problem is gone. And you want to forget as soon as possible that you didn't understand something so obvious and simple from the start....

Inserting an image is not logical:  I couldn't figure out 'when' the (+) sign appears next to text. At first I tried to to modify an existing page (the homepage) and couldn't insert any image, but you have to know you first have to go into the last text block at the end and then press enter to create a new empty text block and only on an empty block there's the option to convert it to other media. duh.

From just visually inspecting the page, checking menu's or typing text in existing blocks you get no visual feedback at all this is "the way".

![add_image](https://user-images.githubusercontent.com/394784/54439581-5a960580-4739-11e9-9c41-55d529f2000f.png)

One easy way to fix this would be to always keep an empty block with the (+) symbol once you are in editing mode. 

If you create a new page first instead of modifying the homepage,  the (+) symbol is there, but even then I succeeded in wandering around Volto for 10 more minutes because my first response was to fill the element with text and feeling silly wondering where the (+) button went. 

Having an insert something option at the bottom of the editor would also have made the next task easier: Once I add an image block, I couldn't start a new text block below it, except for:

*  first creating an empty text block above the image, 
* then first type some text in it because otherwise there's no drag handle
* and then dragging it below the image
* now delete or replace the text.
 
which feels like a work around.

![Add_text_below_image](https://user-images.githubusercontent.com/394784/54440057-43a3e300-473a-11e9-8843-389cb735bd2c.png)

**Comment by tisto** [comment]
fyi: medium shows the plus symbol right from the start.

![New story – Medium](https://user-images.githubusercontent.com/632105/59404053-6aa79a80-8da5-11e9-831d-9ef167688dbc.png)

**Comment by fredvd** [comment]
Follow up/duplicate in #1272

**Comment by tisto** [comment]
@fredvd tbh, I think this issue is more severe than #1272. #1272 is an edge case if your browser window is too narrowed. This is a UX issue that every single Volto user will run into. In addition, this one is fixable without going Quanta "all-in".

There are small amendments that would help:

- increasing the contrast of the "+" icon
- moving the "+" icon to the right inside the block (more like Gutenberg)

![The-new-Gutenberg-editing-experience (1)](https://user-images.githubusercontent.com/632105/144806421-7f84df82-81fd-4b6f-987f-27db7cf0009b.png)

- implementing the Quanta "+" icon (move it below the current block, I am actually not sure how Quanta is supposed to behave when the user clicks into the first text block):

![Add page - Blank frist time](https://user-images.githubusercontent.com/632105/144806640-78ae1d7e-1b8a-4c0f-979a-5b1653ce78f5.png)

Maybe @sneridagh can shed some light into the current discussion with Albert on that topic.

**Comment by fredvd** [comment]
@tisto You're right.  I was searching for one of my issues in the repo this weekend. I saw other issues I started and tried to do some cleanup for things I submitted already long ago that were already fixed or in progress. But I didn't reread these carefully, these are indeed different situations.

I chatted with @sneridagh in Sorrento about this issue & Quanta and he mentionned the (+) issue was going to be solved in Quanta because of a different location. But this issue is about the (+) for example not appearing at all at the end of the page until you've created an empty text block there.  So as a first time user you have no visual clue on how to continue. 

@sneridagh Having a + in the toolbar (from what I understood from you is one of the changes in Quanta, but we only chatted briefly) will fix the 'intra' block insert on other places on the page and #1272 , but still not solve the append at the end of the page. 

Allthough you could argue that if you select the last block the + will also appear there, so it's one action less  (now it's select the block, enter to create a new empty text block and you see the +.   Having a (+) always visible is IMHO the best solution, but it will stay a balance between 'clean' and 'obvious on how to use'.

**Comment by djay** [comment]
I came across this issue because I couldn't work out how to insert into an existing home page. It might be a bug but from above it seems like there is no concept of inserting into a middle of a page?

I would expect to see a + next to the tag or at the right. Notion has it on the left and allows inserting below.

![image](https://user-images.githubusercontent.com/41700/198261635-e4b9e81d-15b1-4882-9915-15b0b96bc9b3.png)

**Comment by tiberiuichim** [comment]
@djay It's unintuitive. Two ways to do it: 

- either create the image at the bottom of the page and drag it up in the middle
- select the block above the "future place of your image" and hit Enter, which should insert a new block at that position

**Comment by djay** [comment]
@tiberiuichim ok. in my particular case this seems to be a bug in the theme thats preventing the empty block from appearing as you can see

![image](https://user-images.githubusercontent.com/41700/198452202-bcdf36d4-3277-45e9-89cb-228d011b430c.png)

However I think that @fredvd pointed out this is still not a good design decision. Essentially what the + button currently is a "turn into" button rather than an insert and whats more it's a special case that only applies to this special empty block at the bottom. In addition there seems to be this insert action (pressing enter) that has no corresponding visible button.

I know I'm coming to this this late but I'm going to get my developers to work on a patch as I believe this is issue is important than it might seem and should be tried to be fixed for plone 6. 

What I propose is

- put a [+] next to the drag tag like in notion. This is an "insert after" button. It lets you pick what you will insert after.
   - we can also put this button into the settings but I don't think putting it there alone is going to be enough. Users will look at the block itself on how to insert something before or after it. they are less likely to look at the settings and def not likely to look at the bottom of the page.
- there won't be an automatic empty block at the bottom of the page if the page already has blocks
- for a empty page we will have an empty text block rather than an this special empty block. so it's [+] will be an insert after. so if you want say and image on the page with no text then it would be two actions. insert image below and then delete the unwanted text block. but I think that's an acceptable tradeoff and easier to understand
- the enter key is an insert text block below
- later we can support the "turn into" function in addition. This is something that notion does well. They have a menu on the drag button which lets you turn certain kinds of blocks into others, like changing header sizes. they also support / commands to turn a empty  block into something else or insert a new block below if not empty

![image](https://user-images.githubusercontent.com/41700/198461516-04643b7c-cfd8-4096-a8d1-297b3b8edfb6.png)
![image](https://user-images.githubusercontent.com/41700/198461888-dc54df8e-75f6-416f-a3ef-9204de4e78d5.png)

**Comment by djay** [comment]
@tiberiuichim ok. It's not a bug in our particular theme. rereading the original issue and trying it out on default volto the problem is that the only way to insert a block onto an existing page is to press enter on the block above. and if its text block it has to be enter at the end of the paragraph. The chance of a new user discovering this is very unlikely so as @tisto pointed out, this is not a niche problem.

![image](https://user-images.githubusercontent.com/41700/198486801-634e5523-79b0-482a-b908-4aedfe598dcc.png)

**Comment by stevepiercy** [comment]
FWIW, I think the Quanta implementation that @tisto laid out would mostly solve this issue, but I don't agree with a couple of points. I would like to see the following.

- `+` button is displayed on all blocks. This would allow adding or inserting a block anywhere and make it a little more obvious.
- Add `alt` or `title` text to the `+` button that says "Add or insert block after this block (`Enter`)". This will help educate newbie users, making it faster for them to edit pages.
- Keep the `+` on the left side to avoid conflicts with the Trash icon and accidentally deleting a block. Destructive actions should always be isolated in the UI.
- Update the Block menu of shortcuts to include "`Tab` or `Shift-Tab` to navigate between blocks" and "`Enter` to add or insert a block after the current block".

**Comment by rioksane** [comment]
Check out how Squarespace does it. I have used it for some years and find it very easy to use. 

1. It has a plus button all the time on the top right. If you click it, it adds a new block to the bottom of the page. 

2. And when you hover over page elements, its shows where you can add new blocks directly with + button. 
<img width="966" alt="squarespace-ux" src="https://user-images.githubusercontent.com/5127672/198953790-4fdaa54f-8de1-4d97-8ac2-3f1eee0f58ab.png">

When just looking at the page it does not show the hovered pluses, making the view easier to the eye. Showing all the pluses all the time would make the UI cluttered, I think.

Quanta looks nice with the improved + button.
