### ISSUE TITLE
Snapshots on Archive.org not working with Volto based Plone Pages | and ways to Workaround

### ISSUE THREAD

**Issue by acsr** [plone/volto#7199]
#### The bug
Snapshots of Volto based pages on Archive.org are not working and empty.

TODO: @davisagli @polyester Please point to exiting tickets, I did not find them

#### Purpose of this Ticket

I share my recent success to archive Zotero Snaphots on Archive.org

- Zotero 7 uses the technology behind https://www.getsinglefile.com/
- They inject a Javascript snippet at the end of the page from the Browser Plugin side (https://www.getsinglefile.com/ Chrome Addon, Zotero Connector) to make sure the whole page can be loaded.

This does not help to properly cite on archive.org under the correct URL and capture greater amounts of pages.

The issue should be fixed inside of Volto or by adding a Volto Patch Addon, that fixes the issue until the next release adressing the point.

### To Reproduce

1. Go to https://archive.org
2. Click on Web in the top left menu
3. Enter a target URL in the right **Save** field in the Dropdown Megamenu.
or go directly to https://web.archive.org/save and enter url into the field
4. Save / trigger a snapshot 

![Image](https://github.com/user-attachments/assets/2aa73627-79ff-4669-b2e0-f1bb6d172141)

**Expected behavior**
A snapshot is taken, you can see the thumbnail, you can visit and browse the snaphot.

#### Issues

- A DSGVO Banner is spoiling the capture and cannot be removed in the loaded page during capture
- The site is not fully hydrated available when archive.org tries to capture the content

##### Possible Workarounds
- catch calls by archive.org and 
    - block the DSGVO banner (not a Volto issue)
    - force a fully hydrated version of the page

#### Screenshot of the failure
If applicable, add screenshots or videos to help explain your problem.

Report of the snapshot (41 Items downloaded):
``` Text
https://tagung.plone.de/2025
https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015
https://tagung.plone.de/@@site-logo/Plone Tagung 2025 Signet-outline.svg
https://tagung.plone.de/static/css/client.1037cdc6.css
https://tagung.plone.de/static/js/runtime~client.748e8242.js
https://tagung.plone.de/static/js/client.5e0e7a90.js
https://tagung.plone.de/static/media/Inter-Bold.275bfea5.ttf
https://tagung.plone.de/2025/images/koblenz-wide.jpg/@@images/image-1200-f010e4aebb19dc89267bf12981efa803.jpeg
https://tagung.plone.de/2025/tagung/plone-hochschultagung/@@images/preview_image-1600-d3b73e266413379d0782dcda7594c772.jpeg
https://tagung.plone.de/2025/tagung/programm-plone-tagung/@@images/preview_image-1000-252581abcf499ba54edde3fd9586aebc.png
https://tagung.plone.de/2025/sprint/@@images/preview_image-1111-4eedf7148125e739e6c108dee597f480.jpeg
https://tagung.plone.de/static/media/Inter-Light.d55f45d0.ttf
https://tagung.plone.de/++api++/2025/@querystring-search?query={"metadata_fields":"_all","b_size":25,"limit":"2","query":[{"i":"path","o":"plone.app.querystring.operation.string.path","v":"/2025/nachrichten"},{"i":"portal_type","o":"plone.app.querystring.operation.selection.any","v":["News Item"]}],"sort_on":"effective","sort_order":"descending","b_start":0}
https://tagung.plone.de/++api++/2025?expand=breadcrumbs,actions,navroot,navigation,inherit&expand.inherit.behaviors=voltolighttheme.header,voltolighttheme.theme,voltolighttheme.footer,kitconcept.footer,kitconcept.sticky_menu&expand.navigation.depth=3
https://tagung.plone.de/static/media/Inter-Regular.079af0e2.ttf
https://tagung.plone.de/++api++//@querystring-search?query={"query":[{"i":"portal_type","o":"plone.app.querystring.operation.selection.any","v":["Sponsor"]},{"i":"path","o":"plone.app.querystring.operation.string.path","v":"/2025"}],"fullobjects":true,"b_size":25}
https://tagung.plone.de/2025/koblenz/@@images/preview_image-1600-6ae2063ccada2e3f7a9da1989538162c.jpeg
https://tagung.plone.de/static/js/react-ga4.dd3d2678.chunk.js
https://tagung.plone.de/2025/nachrichten/konferenz-website-in-einem-tag-mit-volto-plone/@@images/image-1206-3cb5c928c889e3fcb5818a019fea825c.png
https://tagung.plone.de/2025/sponsoren/kitconcept/@@images/logo-400-d8904fa10d7abaedcd15d11202dcfea5.svg
https://tagung.plone.de/2025/tagung/abendprogramm/@@images/preview_image-1600-4bfdf7fac5274996b0c967daa497a7d6.jpeg
https://tagung.plone.de/2025/nachrichten/playwright-fuer-webanwendungen-tests-screenshots-stabilitaet/@@images/image-1201-317c661b3a62972985e0bc69685eae8d.png
https://tagung.plone.de/2025/sponsoren/syslab.com/@@images/logo-400-19871eee36f436c785acc07a2e44c973.svg
https://tagung.plone.de/2025/sponsoren/zopyx/@@images/logo-400-1e34a66c77fa87127f69971ccaf3ecce.svg
https://tagung.plone.de/2025/sponsoren/interaktiv/@@images/logo-400-fcd23330a7a884ba3dd7f011f2762923.svg
https://tagung.plone.de/2025/sponsoren/starzel/@@images/logo-400-b429ce5478446e3094cd2756fbc8e802.svg
https://tagung.plone.de/2025/sponsoren/novareto/@@images/logo-400-7e163344addae6daf4e5d8bb230f1b44.svg
https://tagung.plone.de/2025/sponsoren/python-software-verband-e-v/@@images/logo-400-9a18f414728be60c9709448001ed7cd2.svg
https://tagung.plone.de/2025/sponsoren/universitaet-koblenz/@@images/logo-400-a54be31f8d1f4154b1473e791f7594b1.svg
https://tagung.plone.de/2025/sponsoren/plone-foundation/@@images/logo-400-8c8979b97761c9d39a961dae2e64a21a.svg
https://tagung.plone.de/2025/sponsoren/derico/@@images/logo-400-d02b1e358be01ac878fe25a6b27f228a.svg
https://tagung.plone.de/2025/sponsoren/acsr-industrialdesign/@@images/logo-400-ae96bbb4342b86ba87ee57ceaf2c133e.svg
https://tagung.plone.de/++api++/2025/@querystring-search?query={"metadata_fields":"_all","b_size":25,"limit":"2","query":[{"i":"path","o":"plone.app.querystring.operation.string.path","v":"/2025/nachrichten"},{"i":"portal_type","o":"plone.app.querystring.operation.selection.any","v":["News Item"]}],"sort_on":"effective","sort_order":"descending","b_start":0}
https://tagung.plone.de/2025/plonetagung-gebaude-e.jpg/@@images/image-1024-cf38b614df49be1fb31cbfaeadb6b995.jpeg
https://tagung.plone.de/2025/tagung/sponsoring/@@images/preview_image-1600-ee61f1f9b71baab84f474dc25e53bc17.jpeg
https://tagung.plone.de/2025/tagung/tickets/@@images/preview_image-800-8b5cb11d678c30547c783760f9d93ede.jpeg
https://tagung.plone.de/2025/tagung/vortrag-einreichen/@@images/preview_image-1280-5ef532649bc77ed0d337c0cab3f71a9c.jpeg
https://tagung.plone.de/2025/overview-in-english/@@images/preview_image-360-ba7f992c894534888ef25fbb27b6043f.png
https://tagung.plone.de/cdn-cgi/rum?
https://tagung.plone.de/icon.svg
https://tagung.plone.de/favicon.ico
```

#### Software (please complete the following information):

- OS: [macOS]
- Browser [chrome
- Volto 18.22.0
- Plone 6.1.1
- plone.restapi 9.13.3
- @kitconcept/volto-light-theme 6.0.1

#### Additional context
The issue was mentioned by @polyester during beethoven sprint 2025.
The same may occur with httrack snapshots, but not tested by me.

### further issues on Archive org

- The capture may be visible a short time, but is spoiled by the DSGVO Banner.
- After Scrolling down a successful display, you cannot scroll back
    - I cannot reprocue if the display was possible due to my personal setup 7 existing cookies or cache data
    - The display cannot be reproduced in a save way suitable for the purpose of archiving. 

### (very Dirty) Workaround

**For me using current Zotero 7 to capture single file snapshots of a Volto page is working fine!**
- you can find and display a successful snapshot of the above page using Zotero in the public Plone library on zotero: 
    - https://www.zotero.org/groups/3197/plone/items/FC8T7KRT
- You can watch the attachment in the browser by logging in using any account into zotero and using the temporary link displayed when hovering over the snapshot attachment of the item in the right sidebar
    - Link starts with https://files.zotero.net/ and contains a log UUID that expires for others
- I could use this link to capture a snapshot from Archive.org that ia publicly available under:
   - This URL is very long! [https://web.archive.org/..](.https://web.archive.org/web/20250616081650/https://files.zotero.net/eyJleHBpcmVzIjoxNzUwMDYxODE0LCJoYXNoIjoiNzY4N2QxNzhkOWNjODQyOWM3MTY0NDMwYjNlNjQ4YWUiLCJpdGVtIjoiMzc4MDhcL1VINFZGMlVTIiwiemlwIjoxLCJjb250ZW50VHlwZSI6InRleHRcL2h0bWwiLCJjaGFyc2V0IjoidXRmLTgifQ%3D%3D/141bf815da9182d938785d5c050602b3b52198b8c55eb741ee248bce116d52dc/2025.html)

#### Snapshots of View on Zotero: 

- Screenshot-Zotero-Attachment-Link
  ![Image](https://github.com/user-attachments/assets/0315b814-1a48-433b-bd10-81ee5c137661)

- Screenshot-Snapshot-Archive.org-of-Zotero
  ![Image](https://github.com/user-attachments/assets/78b7079d-2fb5-4ef7-a696-30a770b0d12b)

**Comment by davisagli** [comment]
@acsr https://github.com/plone/volto/issues/7132 was the issue that Paul opened during the Beethoven Sprint. (The fix was merged but not released yet.)

As for the DSGVO banner, maybe it is possible to hide it by setting similar cookies (`confirm_cookies=1` etc.) on archive.org to what is set on tagung.plone.de after you click through the banner?

**Comment by acsr** [comment]
> [@acsr](https://github.com/acsr) [#7132](https://github.com/plone/volto/issues/7132) was the issue that Paul opened during the Beethoven Sprint. (The fix was merged but not released yet.)
> 
> As for the DSGVO banner, maybe it is possible to hide it by setting similar cookies (`confirm_cookies=1` etc.) on archive.org to what is set on tagung.plone.de after you click through the banner?

I am running a recent Plone 6.1.3 + Volto 18.29.1 + VLT 7.6.1 -> **no fix recognizable**

What I found out is:

- If you trigger a snapshot manually via https://web.archive.org/save, visit the snapshot at once.
- Click away the banner, you still see nothing.
- Then take another snapshot at once by using the back function of the browser to go back to the capture start page.
- Before the second attempt, you get a warning on the capture page that you have repeated the capture within a short time and have to wait 1 hour until the the next try.
- Then the resulting snapshot seems fine. At least for my test.

Need to followup on this later. I have no clue how to fix that without manual interaction or on the server catching requests.

**Comment by acsr** [comment]
Not tested myself in https://github.com/plone/volto/issues/7132 but seems on track
